# Generated by Django 6.0.7 on 2026-10-04 11:30

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_developer_read_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bhk_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1 BHK', '1 BHK'), ('2 BHK', '2 BHK'), ('3 BHK', '3 BHK'), ('4 BHK', '4 BHK'), ('5 BHK', '5 BHK'), ('6 BHK', '6 BHK'), ('7 BHK', '7 BHK'), ('8 BHK', '8 BHK'), ('9 BHK', '9 BHK'), ('10 BHK', '10 BHK'), ('10+ BHK', '10+ BHK'), ('Shop', 'Shop')], max_length=50, null=True),
        ),
    ]
