# Generated by Django 6.0.7 on 2026-09-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_setting_linkexplore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='linkexplore',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
