# Generated by Django 6.0.7 on 2026-10-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_setting_google_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='footer_link_text',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
