# Generated by Django 6.0.7 on 2026-09-28 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_slider_button_text_alter_slider_button_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='button_link',
        ),
    ]
